name: bwa
channels:
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - bcftools=1.8=h4da6232_3
  - bwa=0.7.17=h5bf99c6_8
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2021.10.26=h06a4308_2
  - curl=7.78.0=h1ccaba5_0
  - krb5=1.19.2=hac12032_0
  - libcurl=7.78.0=h0b77cf5_0
  - libdeflate=1.2=h516909a_1
  - libedit=3.1.20210714=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libnghttp2=1.41.0=hf8bcb03_2
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.3=h7f8727e_0
  - openssl=1.1.1l=h7f8727e_0
  - perl=5.26.2=h14c3975_0
  - sambamba=0.5.9=1
  - samtools=1.6=hb116620_7
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
